
# Loader Metadata
modLoader="javafml" # mandatory
loaderVersion="[31,)" # mandatory
issueTrackerURL="https://github.com/alcatrazEscapee/ore-veins/issues" # optional

# Ore Veins
[[mods]] # mandatory
    modId="oreveins" # mandatory
    version="${file.jarVersion}" # mandatory
    displayName="Realistic Ore Veins" # mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-ore-veins" #optional
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="AlcatrazEscapee" #optional
    description='''
    This is a Minecraft mod to add realistically shaped veins of ore to your world. Useful for custom maps, mod packs, or just a different survival experience. Everything is fully configurable via json, meaning you can have ore veins of whatever type of shape or size you want.

    For example images of various types and configurations of veins see the curseforge images. For info on how to configure, see the readme on github.
    '''

# dependencies
[[dependencies.oreveins]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oreveins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"